# Assignment 5: Github Project
Name: Claire Anne Gaspar

### Olympic 2024 Data Merge

This script merges two datasets: 

* "Olympic2024_Medallists.csv" - A dataset containing the medal winners.
* "Olympic2024_Athletes.csv" - A dataset with general athlete information.

Objective:
By merging these datasets, we can enrich the medalist data with additional athlete details such as age, country, and sport.
This allows for deeper analysis, such as understanding the age distribution of medalists or comparing performance by nationality.

Merge Key:
Both datasets share a common key: **'Athlete Code'**, which will be used to combine the information.

### Lets import libraries and load both the datasets

In [4]:
import pandas as pd

In [5]:
# Load the first dataset (Medallists)

medallists_data = pd.read_csv("../data/Olympic2024_Medallists.csv")

In [6]:
medallists_data.head(10)

,medal_date,medal_type,medal_code,name,gender,country_code,country,country_long,nationality,team,team_gender,discipline,event,event_type,url_event,birth_date,code_athlete,code_team
0,2024-07-27,Gold Medal,1.0,EVENEPOEL Remco,Male,BEL,Belgium,Belgium,Belgium,NaN,NaN,Cycling Road,Men's Individual Time Trial,ATH,/en/paris-2024/results/cycling-road/men-s-indi...,2000-01-25,1903136,NaN
1,2024-07-27,Silver Medal,2.0,GANNA Filippo,Male,ITA,Italy,Italy,Italy,NaN,NaN,Cycling Road,Men's Individual Time Trial,ATH,/en/paris-2024/results/cycling-road/men-s-indi...,1996-07-25,1923520,NaN
2,2024-07-27,Bronze Medal,3.0,van AERT Wout,Male,BEL,Belgium,Belgium,Belgium,NaN,NaN,Cycling Road,Men's Individual Time Trial,ATH,/en/paris-2024/results/cycling-road/men-s-indi...,1994-09-15,1903147,NaN
3,2024-07-27,Gold Medal,1.0,BROWN Grace,Female,AUS,Australia,Australia,Australia,NaN,NaN,Cycling Road,Women's Individual Time Trial,ATH,/en/paris-2024/results/cycling-road/women-s-in...,1992-07-07,1940173,NaN
4,2024-07-27,Silver Medal,2.0,HENDERSON Anna,Female,GBR,Great Britain,Great Britain,Great Britain,NaN,NaN,Cycling Road,Women's Individual Time Trial,ATH,/en/paris-2024/results/cycling-road/women-s-in...,1998-11-14,1912525,NaN
5,2024-07-27,Bronze Medal,3.0,DYGERT Chloe,Female,USA,United States,United States of America,United States,NaN,NaN,Cycling Road,Women's Individual Time Trial,ATH,/en/paris-2024/results/cycling-road/women-s-in...,1997-01-01,1955079,NaN
6,2024-07-27,Gold Medal,1.0,OH Sanguk,Male,KOR,Korea,Republic of Korea,Korea,NaN,NaN,Fencing,Men's Sabre Individual,HATH,/en/paris-2024/results/fencing/men-s-sabre-ind...,1996-09-30,1927149,NaN
7,2024-07-27,Silver Medal,2.0,FERJANI Fares,Male,TUN,Tunisia,Tunisia,Tunisia,NaN,NaN,Fencing,Men's Sabre Individual,HATH,/en/paris-2024/results/fencing/men-s-sabre-ind...,1997-07-22,1937783,NaN
8,2024-07-27,Bronze Medal,3.0,SAMELE Luigi,Male,ITA,Italy,Italy,Italy,NaN,NaN,Fencing,Men's Sabre Individual,HATH,/en/paris-2024/results/fencing/men-s-sabre-ind...,1987-07-25,1924595,NaN
9,2024-07-27,Gold Medal,1.0,KONG Man Wai Vivian,Female,HKG,"Hong Kong, China","Hong Kong, China","Hong Kong, China",NaN,NaN,Fencing,Women's Épée Individual,HATH,/en/paris-2024/results/fencing/women-s-epee-in...,1994-02-08,1963262,NaN

In [7]:
# Load the first dataset (Athletes)

athletes_data = pd.read_csv("../data/Olympic2024_Athletes.csv")

In [8]:
athletes_data.head(10)

,code,name,name_short,name_tv,gender,function,country_code,country,country_long,nationality,...,family,lang,coach,reason,hero,influence,philosophy,sporting_relatives,ritual,other_sports
0,1532872,ALEKSANYAN Artur,ALEKSANYAN A,Artur ALEKSANYAN,Male,Athlete,ARM,Armenia,Armenia,Armenia,...,"Father, Gevorg Aleksanyan","Armenian, English, Russian","Gevorg Aleksanyan (ARM), father",He followed his father and his uncle into the ...,"Footballer Zinedine Zidane (FRA), World Cup wi...","His father, Gevorg Aleksanyan","""Wrestling is my life."" (mediamax.am. 18 May 2...",NaN,NaN,NaN
1,1532873,AMOYAN Malkhas,AMOYAN M,Malkhas AMOYAN,Male,Athlete,ARM,Armenia,Armenia,Armenia,...,NaN,Armenian,NaN,NaN,NaN,NaN,"""To become a good athlete, you first have to b...","Uncle, Roman Amoyan (wrestling), 2008 Olympic ...",NaN,NaN
2,1532874,GALSTYAN Slavik,GALSTYAN S,Slavik GALSTYAN,Male,Athlete,ARM,Armenia,Armenia,Armenia,...,NaN,Armenian,Personal: Martin Alekhanyan (ARM).<br>National...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1532944,HARUTYUNYAN Arsen,HARUTYUNYAN A,Arsen HARUTYUNYAN,Male,Athlete,ARM,Armenia,Armenia,Armenia,...,"Wife, Diana (married October 2022). Daughter, ...",Armenian,National: Habetnak Kurghinyan,While doing karate he noticed wrestlers traini...,"Wrestler Armen Nazaryan (ARM, BUL), two-time O...",NaN,"“Nothing is impossible, set goals in front of ...",NaN,NaN,NaN
4,1532945,TEVANYAN Vazgen,TEVANYAN V,Vazgen TEVANYAN,Male,Athlete,ARM,Armenia,Armenia,Armenia,...,"Wife, Sona (married November 2023)","Armenian, Russian",National: Habetnak Kurghinyan (ARM),“My family did not like wrestling very much. A...,NaN,NaN,NaN,NaN,NaN,NaN
5,1532951,ARENAS Lorena,ARENAS L,Lorena ARENAS,Female,Athlete,COL,Colombia,Colombia,Colombia,...,"Father, Jose Otoniel. Mother, Maria Rudy. Has ...",Spanish,Personal: Brent Vallance (AUS),NaN,"Race walker Luis Fernando Lopez (COL), four-ti...",NaN,NaN,NaN,In competition she wears a ring or earrings he...,NaN
6,1533112,McKENZIE Ashley,McKENZIE A,Ashley McKENZIE,Male,Athlete,JAM,Jamaica,Jamaica,Jamaica,...,"One daughter, Lana-Rose, who lives in France",English,Personal and National: Luke Preston (GBR),"""I was thrown over [an argument about] a Pokem...","Boxer Muhammad Ali, born Cassius Clay (USA), f...","""My coach Luke Preston. We've been a team for ...",NaN,NaN,NaN,NaN
7,1533136,BASS BITTAYE Gina Mariam,BASS BITTAYE GM,Gina Mariam BASS BITTAYE,Female,Athlete,GAM,Gambia,Gambia,Gambia,...,"Husband, Mustapha Bittaye - physical education...","English, French",Personal: Christophe Belliard (FRA),“I started running when I was in primary schoo...,"Sprinter Shelly-Ann Fraser-Pryce (JAM), three ...",NaN,"""If you believe in yourself, never be discoura...",NaN,NaN,NaN
8,1533176,CAMARA Ebrahima,CAMARA E,Ebrahima CAMARA,Male,Athlete,GAM,Gambia,Gambia,Gambia,...,Married. One daughter. Has three brothers,"Arabic, English, French, Mandinka, Wolof",Personal: Christophe Belliard (FRA),"""I love running and I was fast a child."" (Athl...","Sprinter Gina Mariam Bass Bittaye (GAM), two-t...","Momodou Lamin Kujabi, a former international a...","""What does not kill you makes you stronger."" (...",NaN,NaN,NaN
9,1533188,RUEDA SANTOS Lizeth,RUEDA SANTOS L,Lizeth RUEDA SANTOS,Female,Athlete,MEX,Mexico,Mexico,Mexico,...,NaN,Spanish,Personal: Eugenio Chimal (MEX),Was a competitive swimmer from age 12 and went...,NaN,NaN,NaN,NaN,NaN,Competed in marathon swimming at London 2012. ...

In [9]:
print("Medallists Data Columns:", medallists_data.columns)
print("Athletes Data Columns:", athletes_data.columns)

Medallists Data Columns: Index(['medal_date', 'medal_type', 'medal_code', 'name', 'gender',
       'country_code', 'country', 'country_long', 'nationality', 'team',
       'team_gender', 'discipline', 'event', 'event_type', 'url_event',
       'birth_date', 'code_athlete', 'code_team'],
      dtype='object')
Athletes Data Columns: Index(['code', 'name', 'name_short', 'name_tv', 'gender', 'function',
       'country_code', 'country', 'country_long', 'nationality',
       'nationality_full', 'nationality_code', 'height', 'weight',
       'disciplines', 'events', 'birth_date', 'birth_place', 'birth_country',
       'residence_place', 'residence_country', 'nickname', 'hobbies',
       'occupation', 'education', 'family', 'lang', 'coach', 'reason', 'hero',
       'influence', 'philosophy', 'sporting_relatives', 'ritual',
       'other_sports'],
      dtype='object')

Since the dataset has different column header we need to rename the other one

In [ ]:
# Rename the column in athletes_data to match medallists_data
athletes_data.rename(columns={"code": "code_athlete"}, inplace=True)

In [ ]:
# Now merge two datasets

merged_datasets = pd.merge(medallists_data, athletes_data, on="code_athlete", how="inner")

In [ ]:
print("Merge successful! Merged dataset has", merged_datasets.shape[0], "rows and", merged_datasets.shape[1], "columns.")

In [ ]:
merged_datasets.head()

In [ ]:
merged_datasets.to_csv("BABI4005_GitProject/clean_data/Olympics2024_MergedData.csv", index=False)